
spring:
  application:
    name: demo-oauth-client

server:
  port: 8767        #指定改Eureka实例的端口
  context-path: /client

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


security:
  sessions: stateless
  oauth2:
    resource:
      loadBalanced: true
      user-info-uri: http://demo-oauth-gateway/auth/user
      prefer-token-info: false
      service-id: demo-oauth-client


hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
