spring:
  application:
    name: demo-oauth-server
server:
  port: 8766        #指定改Eureka实例的端口
  context-path: /auth
security:
  sessions: stateless

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
