
spring:
  application:
    name: demo-oauth-gateway

server:
  port: 8765        #指定改Eureka实例的端口
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


zuul:
  ignored-services: '*'
  routes:
    oauth-server:
      path: /auth/**
      serviceId: demo-oauth-server
      sensitiveHeaders:
      strip-prefix: false

    oauth-client:
      path: /client/**
      serviceId: demo-oauth-client
      sensitiveHeaders:
      strip-prefix: false


#使用下面报404
#zuul:
#  ignoredServices: '*'
#  routes:
##   这里的名称要跟  服务的名称一致
#    demo-oauth-server: /auth/**
#    demo-oauth-client: /client/**
#  sensitive-headers:


hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000