
#server:
#  port: 8761        #指定改Eureka实例的端口
#eureka:
#  server:
##    enable-self-preservation: false # 关闭自我保护
##    eviction-interval-timer-in-ms: 3000  #清理时间间隔 默认是60*1000
#  instance:
#    prefer-ip-address: true  #设置显示IP
#    hostname:  localhost
#    lease-renewal-interval-in-seconds:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#security:
#  basic:
#    enabled: false



server:
  port: 8761

spring:
  application:
    name: eureka-service

eureka:
  instance:
    # 使用IP注册
    prefer-ip-addree: true
    hostname: localhost
    # 心跳间隔
    lease-renewal-interval-in-seconds: 3
    # 服务失效时间， 如果多久没有收到请求，则可以删除服务
    lease-expiration-duration-in-seconds: 7
  client:
    #是否将自身注册到eureka服务器中
    register-with-eureka: true
    # 是否从eureka服务器中获取注册信息
    fetch-registry: false
    # 从注册中心获取实例注册服务的信息
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

  server:
    #关闭自我保护模式
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 3000
    # 设置如果Eureka Server启动时无法从临近Eureka Server节点获取注册信息，它多久不对外提供注册服务
#    wait-time-in-ms-when-sync-empty: 6000000
    # 集群之间相互更新节点信息的时间频率
#    peer-eureka-nodes-update-interval-ms: 60000
