
server:
  port: 8762        #指定改Eureka实例的端口
eureka:
  instance:
#    lease-renewal-interval-in-seconds: 10 #租期更新时间间隔（默认30秒）
#    lease-expiration-duration-in-seconds: 30 #租期到期时间（默认90秒）
    service-url:
      defaultZone: http://10.15.21.114:8761/eureka/
spring:
  application:
    name: demo-ribbon-service